# fly.toml app configuration file generated for basiccrm on 2023-05-05T14:05:01+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "basiccrm"
primary_region = "syd"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "DockerFile"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
